# Worksheet 04

Name:  
UID: 

### Topics

- Distance & Similarity

### Distance & Similarity

#### Part 1

a) In the minkowski distance, describe what the parameters p and d are.

d is the dimensional of the space
p is the order of the distance, so p=1 is like a manhattan distance, p=2 is like euclidian distance, etc.


b) In your own words describe the difference between the Euclidean distance and the Manhattan distance.

manhattan distance only uses vectors that are orthogonal to each other and parrael to axises to reach a point
euclidean distance uses one vector that is at a specfific angle

Consider A = (0, 0) and B = (1, 1). When:

- p = 1, d(A, B) = 2
- p = 2, d(A, B) = $\sqrt{2} = 1.41$
- p = 3, d(A, B) = $2^{1/3} = 1.26$
- p = 4, d(A, B) = $2^{1/4} = 1.19$

c) Describe what you think distance would look like when p is very large.

Given the way the example is trending, I would say it will go toward equaling 1.

d) Is the minkowski distance still a distance function when p < 1? Expain why / why not.

No.  It violates the triangle inequality.

e) when would you use cosine similarity over the euclidan distance?

Higher dimensional data.

f) what does the jaccard distance account for that the manhattan distance doesn't?

jaccard distance is specifically for set-related similarity, such as differences in elements between sets, while the manhattan distance focuses on the absolute differences between corresponding elements of vectors or sets.

#### Part 2

Consider the following two sentences:

In [1]:
s1 = "hello my name is Alice"  
s2 = "hello my name is Bob"

using the union of words from both sentences, we can represent each sentence as a vector. Each element of the vector represents the presence or absence of the word at that index.

In this example, the union of words is ("hello", "my", "name", "is", "Alice", "Bob") so we can represent the above sentences as such:

In [2]:
v1 = [1,    1, 1,   1, 1,    0]
#     hello my name is Alice
v2 = [1,    1, 1,   1, 0, 1]
#     hello my name is    Bob

Programmatically, we can do the following:

In [4]:
corpus = [s1, s2]
all_words = list(set([item for x in corpus for item in x.split()]))
print(all_words)
v1 = [1 if x in s1 else 0 for x in all_words]
print(v1)

['Alice', 'name', 'my', 'Bob', 'hello', 'is']
[1, 1, 1, 0, 1, 1]


Let's add a new sentence to our corpus:

In [5]:
s3 = "hi my name is Claude"
corpus.append(s3)
print(corpus)

['hello my name is Alice', 'hello my name is Bob', 'hi my name is Claude']


a) What is the new union of words used to represent s1, s2, and s3?

In [7]:
all_words = list(set([item for x in corpus for item in x.split()]))
v1 = [1 if x in s1 else 0 for x in all_words]
print(v1)
v2 = [1 if x in s2 else 0 for x in all_words]
print(v2)
v3 = [1 if x in s3 else 0 for x in all_words]
print(v3)

[0, 1, 1, 1, 0, 0, 1, 1]
[0, 0, 1, 1, 1, 0, 1, 1]
[1, 0, 1, 1, 0, 1, 0, 1]


b) Represent s1, s2, and s3 as vectors as above, using this new set of words.

c) Write a function that computes the manhattan distance between two vectors. Which pair of vectors are the most similar under that distance function?

In [8]:
def minkowski(x, y, p):
    if len(x) != len(y):
        raise RuntimeError("x and y should be the same dimension")
    res = 0
    for i in range(len(x)):
        res += abs(x[i]-y[i]) ** p
    return res ** (1/p)

print(minkowski([0,0],[1,1],2))
print(minkowski([0,0],[1,1],1))
        

1.4142135623730951
2.0


d) Create a matrix of all these vectors (row major) and add the following sentences in vector form:

- "hi Alice"
- "hello Claude"
- "Bob my name is Claude"
- "hi Claude my name is Alice"
- "hello Bob"

In [13]:
s1 = "hi Alice"  
s2 = "hello Claude"
s3 = "Bob my name is Claude"
s4 = "hi Claude my name is Alice"
s5 = "hello Bob"
corpus = [s1, s2, s3, s4, s5]
matrix = []
all_words = list(set([item for x in corpus for item in x.split()]))
v1 = [1 if x in s1 else 0 for x in all_words]
v2 = [1 if x in s2 else 0 for x in all_words]
v3 = [1 if x in s3 else 0 for x in all_words]
v4 = [1 if x in s4 else 0 for x in all_words]
v5 = [1 if x in s5 else 0 for x in all_words]

matrix.append(v1)
matrix.append(v2)
matrix.append(v3)
matrix.append(v4)
matrix.append(v5)

print(matrix)

[[1, 1, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 1, 1, 0], [0, 0, 1, 1, 1, 1, 0, 1], [1, 1, 1, 1, 0, 1, 0, 1], [0, 0, 0, 0, 1, 0, 1, 0]]


e) How many rows and columns does this matrix have?

In [ ]:
# 5 rows, one for each data point
# 8 columns, one for each unique word in the corpus

f) When using the Manhattan distance, which two sentences are the most similar?

In [22]:

min_dis = 10000
min_vec = []

for vec1 in matrix:
    for vec2 in matrix:
        if (vec1 != vec2):
            temp_dis = (minkowski(vec1, vec2,1))
            if temp_dis < min_dis:
                min_dis = temp_dis
                min_vec = [vec1, vec2]
    
print(min_vec, min_dis)

# v2 and v5 so hello claude and hello bob (makes sense they are only 1 word away)

[[0, 0, 0, 0, 0, 1, 1, 0], [0, 0, 0, 0, 1, 0, 1, 0]] 2.0


#### Part 3 Challenge

Given a set of graphs $\mathcal{G}$, each graph $G \in \mathcal{G}$ is defined over the same set of nodes $V$. The graphs are represented by their adjacency matrices, which are 2D arrays where each element indicates whether a pair of nodes is connected by an edge.

Your task is to compute the pairwise distances between these graphs based on a specific distance metric. The distance $d(G, G')$ between two graphs $G = (V, E)$ and $G' = (V, E')$ is defined as the sum of the number of edges in $G$ but not in $G'$, and the number of edges in $G'$ but not in $G$. Mathematically, this can be expressed as:

$$
d(G, G') = |E \setminus E'| + |E' \setminus E|.
$$

##### Requirements:
1. **Input**: Should take a list of 2D numpy arrays as input. Each array represents the adjacency matrix of a graph.

2. **Output**: Should output a pairwise distance matrix. If there are $n$ graphs in the input list, the output should be an $n \times n$ matrix where the entry at position $(i, j)$ represents the distance between the $i^{th}$ and $j^{th}$ graph.

In [31]:
import numpy as np

def graph_distance_matrix(graphs):
    n = len(graphs)
    distance_matrix = np.zeros((n, n), dtype=int)

    for i in range(n):
        for j in range(n):
            if i != j:
                edges_i = set(zip(*np.where(graphs[i] == 1)))
                edges_j = set(zip(*np.where(graphs[j] == 1)))
              #  print(edges_i, edges_j)
                distance_matrix[i, j] = len(edges_i - edges_j) + len(edges_j - edges_i)

    return distance_matrix

graph1 = np.array([[0, 1, 1],
                   [1, 0, 0],
                   [1, 0, 0]])

graph2 = np.array([[0, 1, 1],
                   [1, 0, 1],
                   [1, 1, 0]])

graph3 = np.array([[0, 1, 0],
                   [1, 0, 1],
                   [0, 1, 0]])

graph4 = np.array([[0, 1, 1],
                   [1, 0, 1],
                   [1, 1, 0]])

graphs_list = [graph1, graph2, graph3, graph4]
distance_matrix = graph_distance_matrix(graphs_list)

# Display the result
print("Pairwise Distance Matrix:")
print(distance_matrix)

graphA = np.array([[0, 1, 1],
                   [1, 0, 1],
                   [1, 1, 0]])

graphB = np.array([[0, 1, 0],
                   [1, 0, 0],
                   [0, 0, 0]])

graphC = np.array([[0, 1, 1],
                   [1, 0, 1],
                   [1, 1, 0]])

# List of graphs
graphs_list2 = [graphA, graphB, graphC]

# Calculate pairwise distance matrix
distance_matrix2 = graph_distance_matrix(graphs_list2)

# Display the result
print("Pairwise Distance Matrix:")
print(distance_matrix2)


Pairwise Distance Matrix:
[[0 2 4 2]
 [2 0 2 0]
 [4 2 0 2]
 [2 0 2 0]]
Pairwise Distance Matrix:
[[0 4 0]
 [4 0 4]
 [0 4 0]]
